from sklearn.datasets import fetch_california_housing
import matplotlib.pyplot as plt

housing = fetch_california_housing(as_frame=True)
X = housing.data
y = housing.target

fig, ax = plt.subplots() # when you want to tweak something that was auto generated by pandas or seaborn, this is the best way to do it.
X['MedInc'].hist(ax=ax)
ax.set_title('Histogram')


plt.show()